config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "tops#index"
  resources :opuses do
    resources :comments, only: [:create]
    collection do
      get 'search'
    end
  end
  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'
  resources :items do
    resources :item_comments, only: [:create]
    resources :orders, only: [:index, :create]
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show, :edit, :update, :destroy, :index] do
    get 'likes/index' => 'likes#index', as: 'index_like' 
  end
  # resources :likes, only: [:index]
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :record
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :opus
  validates :text, presence: true
end

app/models/days_to_ship.rb
class DaysToShip < ActiveHash::Base
  self.data = [
    {id: 1 , name: "--" },
    {id: 2 , name: "1~2日" },
    {id: 3 , name: "3~4日" },
    {id: 4 , name: "5~8日" },
    {id: 5 , name: "9~20日" }
  ]
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'Rapper' },
    { id: 3, name: 'DJ' },
    { id: 4, name: 'Graffiti artist' },
    { id: 5, name: 'Track maker' },
    { id: 6, name: 'Dancer' },
    { id: 7, name: 'Producer' },
    { id: 8, name: 'Other' }
  ]
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many  :item_comments, dependent: :destroy
  has_many  :records
  has_one_attached :image
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :days_to_ship
  with_options presence: true, numericality: {other_than: 1} do
    validates :days_to_ship_id
  end
  with_options presence: true do
    validates :name, length: { in: 1..50 }
    validates :text, length: { in: 1..500 }
    validates :image
    validates :price, numericality: { greater_than_or_equal_to: 300, less_than_or_equal_to: 9_999_999, message: 'is out of setting range' }
  end
end

app/models/item_comment.rb
class ItemComment < ApplicationRecord
  belongs_to :user
  belongs_to :item
  validates :text, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :opus
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/opus.rb
class Opus < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_one_attached :image
  has_many :likes
  has_many :users, through: :likes
  with_options presence: true do
    validates :title, length: { in: 1..50 }
    validates :description, length: { in: 1..500 }
  end
  validates :video_or_image, presence: true

  def self.search(search)
    if search != ""
      Opus.where('title LIKE(?)', "%#{search}%")
    else
      Opus.all
    end
  end
  private
  def video_or_image
    youtube_url.present? || image.present?
  end
end

app/models/order.rb
class Order
  include ActiveModel::Model
  attr_accessor :postal_code, :prefecture_id, :municipality, :address, :building_name, :phone_number, :token, :user_id, :item_id
  with_options presence: true do
    validates :postal_code, format: {with: /\A[0-9]{3}-[0-9]{4}\z/, message: "is invalid. Include hyphen(-)"}
    validates :prefecture_id, numericality: { other_than: 1 }
    validates :municipality
    validates :address
    validates :phone_number, format: {with: /\A\d{10,11}\z/, message: "ハイフン不要"}
    validates :token
  end
  def save
    record = Record.create(user_id: user_id, item_id: item_id)
    Address.create(postal_code: postal_code, prefecture_id: prefecture_id, municipality: municipality, address: address, building_name: building_name, phone_number: phone_number, record_id: record.id) 
  end
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '北海道' },
    { id: 3, name: '青森県' },
    { id: 4, name: '岩手県' },
    { id: 5, name: '宮城県' },
    { id: 6, name: '秋田県' },
    { id: 7, name: '山形県' },
    { id: 8, name: '福島県' },
    { id: 9, name: '茨城県' },
    { id: 10, name: '栃木県' },
    { id: 11, name: '群馬県' },
    { id: 12, name: '埼玉県' },
    { id: 13, name: '千葉県' },
    { id: 14, name: '東京都' },
    { id: 15, name: '神奈川県' },
    { id: 16, name: '新潟県' },
    { id: 17, name: '富山県' },
    { id: 18, name: '石川県' },
    { id: 19, name: '福井県' },
    { id: 20, name: '山梨県' },
    { id: 21, name: '長野県' },
    { id: 22, name: '岐阜県' },
    { id: 23, name: '静岡県' },
    { id: 24, name: '愛知県' },
    { id: 25, name: '三重県' },
    { id: 26, name: '滋賀県' },
    { id: 27, name: '京都府' },
    { id: 28, name: '大阪府' },
    { id: 29, name: '兵庫県' },
    { id: 30, name: '奈良県' },
    { id: 31, name: '和歌山県' },
    { id: 32, name: '鳥取県' },
    { id: 33, name: '島根県' },
    { id: 34, name: '岡山県' },
    { id: 35, name: '広島県' },
    { id: 36, name: '山口県' },
    { id: 37, name: '徳島県' },
    { id: 38, name: '香川県' },
    { id: 39, name: '愛媛県' },
    { id: 40, name: '高知県' },
    { id: 41, name: '福岡県' },
    { id: 42, name: '佐賀県' },
    { id: 43, name: '長崎県' },
    { id: 44, name: '熊本県' },
    { id: 45, name: '大分県' },
    { id: 46, name: '宮崎県' },
    { id: 47, name: '鹿児島県' },
    { id: 48, name: '沖縄県' }
  ]
end

app/models/record.rb
class Record < ApplicationRecord
belongs_to :user
belongs_to :item
has_one :address
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :genre
  has_many  :comments
  has_many  :item_comments, dependent: :destroy
  has_one_attached :image
  validates :image, presence: true
  validates :nickname, presence: true
  validates :prefecture, presence: true
  validates :prefecture_id, numericality: { other_than: 1 }
  validates :genre_id,  numericality: { other_than: 1 }
  has_many :opuses, dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :likes
  has_many :like_opuses, through: :likes, source: :opus
  def liked_by?(opus_id)
    likes.where(opus_id: opus_id).exists?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @opuses = @user.opuses.order("created_at DESC")
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    if @user.id == current_user.id
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end
  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to action: :show
    else
      render "edit"
    end  
  end
  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to new_user_registration_path
    else
      renser action: :show
    end
  end


  private
  def user_params
    params.require(:user).permit(:nickname, :prefecture_id, :genre_id, :profile, :image)
  end
  
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/opuses_helper.rb
module OpusesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= render "shared/header.header" %>
<div class="user-edit">
  <div class="user-form">
      <%= bootstrap_form_with model: @user, local: true do |f| %>
        <%= render '/shared/error_messages', model: f.object %>
        <div class="form-group">
        <%= f.text_field :nickname, placeholder: "nickname", rows: "10" %>
        </div>
        
        <%# <div class="form-group"> %>
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}) %>
        <%# </div> %>
        <%# <div class="field"> %>
        <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}) %>
        <%# </div> %>
        <%= f.file_field :image %>
        <%= f.text_area :profile, autofocus: true, placeholder: "profile", rows: "5" %>
        <button type="submit" class="btn btn-primary">Save</button>
      <% end %>
  </div>
  
</div>

app/views/users/show.html.erb
<%= render "shared/header.header" %>
<div class="user-show-contents">
     <div class="userflexbox">
         <div class="userbox1">
          <div id="user-show-left">
           <div id="user-left-box1">
            <%= image_tag @user.image %>
           </div>
           <div class="user-left-box">
            <div class="user-left-box2">
            <p>Artist-Name : <%= @user.nickname %></p>
            </div>
           </div>
           <div class="user-left-box">
           <div class="user-left-box2">
            <p>Genre : <%= @user.genre.name %></p>
            </div>
           </div>
           <div class="user-left-box">
           <div class="user-left-box2">
             <p>Area of ​​activity : <%= @user.prefecture.name %></p>
            </div>
           </div>
           <div class="user-left-box">
           <div class="user-left-box3">
            <p><%= @user.profile %></p>
            </div>
           </div>
           <div class="user-left-box">
           <div class="user-left-box4">
                <% if @user.id == current_user.id %>
                  <%= link_to "新作投稿", new_opus_path, class:"btn btn-success btn-lg" %>
                  <%= link_to "編集する", edit_user_path(@user.id), class:"btn btn-primary btn-lg" %>
                  <%= link_to "アカウント削除", user_path(@user.id), method: :delete, class:"btn btn-danger btn-lg"%>
                  <% else %>

                  <% if @isRoom == true %>
                    <%= link_to "チャットへ", room_path(@roomId), class: "btn btn-primary btn-lg" %>
                  <% else %>
                    <%= form_for @room do |f| %>
                      <%= fields_for @entry do |e| %>
                        <%= e.hidden_field :user_id, :value=> @user.id %>
                      <% end %>
                        <button class="btn btn-primary btn-lg">チャットを始める</button>
                      <%# <button type="button" class="btn btn-success"><%= f.submit "チャットを始める" %>
                      
                    <% end %>
                  <% end %>
                <% end %>
            </div>
           </div>

          </div>
         </div>
         <div class="userbox2">
            <ul id="user-show-opuses">
            <% @opuses.each do |opus| %>
              <li id="user-show-opus">
                <div id="user-show-opus-top">
                <% if opus.youtube_url.present? %>
                  <iframe width="200" height="200" src="https://www.youtube.com/embed/<%= opus.youtube_url%>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                <% else %>
                  <%= image_tag opus.image, :size => '320x480', class: 'item-img' if opus.image.attached? %>
                <% end %>
                </div>
                <div id="user-show-opus-title">
                  <%= link_to opus.title, opus_path(opus.id), class: "btn btn-outline-dark" %>
                </div>
              </li>
            <% end %>
            </ul>
         </div>
     </div>
 </div>