config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "tops#index"
  resources :opuses do
    resources :comments, only: [:create]
    collection do
      get 'search'
    end
  end
  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'
  resources :items do
    resources :item_comments, only: [:create]
    resources :orders, only: [:index, :create]
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show, :edit, :update, :destroy, :index] do
    get 'likes/index' => 'likes#index', as: 'index_like' 
  end
  # resources :likes, only: [:index]
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :record
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :opus
  validates :text, presence: true
end

app/models/days_to_ship.rb
class DaysToShip < ActiveHash::Base
  self.data = [
    {id: 1 , name: "--" },
    {id: 2 , name: "1~2日" },
    {id: 3 , name: "3~4日" },
    {id: 4 , name: "5~8日" },
    {id: 5 , name: "9~20日" }
  ]
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'Rapper' },
    { id: 3, name: 'DJ' },
    { id: 4, name: 'Graffiti artist' },
    { id: 5, name: 'Track maker' },
    { id: 6, name: 'Dancer' },
    { id: 7, name: 'Producer' },
    { id: 8, name: 'Other' }
  ]
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many  :item_comments, dependent: :destroy
  has_many  :records
  has_one_attached :image
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :days_to_ship
  with_options presence: true, numericality: {other_than: 1} do
    validates :days_to_ship_id
  end
  with_options presence: true do
    validates :name, length: { in: 1..50 }
    validates :text, length: { in: 1..500 }
    validates :image
    validates :price, numericality: { greater_than_or_equal_to: 300, less_than_or_equal_to: 9_999_999, message: 'is out of setting range' }
  end
end

app/models/item_comment.rb
class ItemComment < ApplicationRecord
  belongs_to :user
  belongs_to :item
  validates :text, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :opus
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/opus.rb
class Opus < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_one_attached :image
  has_many :likes
  has_many :users, through: :likes
  with_options presence: true do
    validates :title, length: { in: 1..50 }
    validates :description, length: { in: 1..500 }
  end
  validates :video_or_image, presence: true

  def self.search(search)
    if search != ""
      Opus.where('title LIKE(?)', "%#{search}%")
    else
      Opus.all
    end
  end
  private
  def video_or_image
    youtube_url.present? || image.present?
  end
end

app/models/order.rb
class Order
  include ActiveModel::Model
  attr_accessor :postal_code, :prefecture_id, :municipality, :address, :building_name, :phone_number, :token, :user_id, :item_id
  with_options presence: true do
    validates :postal_code, format: {with: /\A[0-9]{3}-[0-9]{4}\z/, message: "is invalid. Include hyphen(-)"}
    validates :prefecture_id, numericality: { other_than: 1 }
    validates :municipality
    validates :address
    validates :phone_number, format: {with: /\A\d{10,11}\z/, message: "ハイフン不要"}
    validates :token
  end
  def save
    record = Record.create(user_id: user_id, item_id: item_id)
    Address.create(postal_code: postal_code, prefecture_id: prefecture_id, municipality: municipality, address: address, building_name: building_name, phone_number: phone_number, record_id: record.id) 
  end
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '北海道' },
    { id: 3, name: '青森県' },
    { id: 4, name: '岩手県' },
    { id: 5, name: '宮城県' },
    { id: 6, name: '秋田県' },
    { id: 7, name: '山形県' },
    { id: 8, name: '福島県' },
    { id: 9, name: '茨城県' },
    { id: 10, name: '栃木県' },
    { id: 11, name: '群馬県' },
    { id: 12, name: '埼玉県' },
    { id: 13, name: '千葉県' },
    { id: 14, name: '東京都' },
    { id: 15, name: '神奈川県' },
    { id: 16, name: '新潟県' },
    { id: 17, name: '富山県' },
    { id: 18, name: '石川県' },
    { id: 19, name: '福井県' },
    { id: 20, name: '山梨県' },
    { id: 21, name: '長野県' },
    { id: 22, name: '岐阜県' },
    { id: 23, name: '静岡県' },
    { id: 24, name: '愛知県' },
    { id: 25, name: '三重県' },
    { id: 26, name: '滋賀県' },
    { id: 27, name: '京都府' },
    { id: 28, name: '大阪府' },
    { id: 29, name: '兵庫県' },
    { id: 30, name: '奈良県' },
    { id: 31, name: '和歌山県' },
    { id: 32, name: '鳥取県' },
    { id: 33, name: '島根県' },
    { id: 34, name: '岡山県' },
    { id: 35, name: '広島県' },
    { id: 36, name: '山口県' },
    { id: 37, name: '徳島県' },
    { id: 38, name: '香川県' },
    { id: 39, name: '愛媛県' },
    { id: 40, name: '高知県' },
    { id: 41, name: '福岡県' },
    { id: 42, name: '佐賀県' },
    { id: 43, name: '長崎県' },
    { id: 44, name: '熊本県' },
    { id: 45, name: '大分県' },
    { id: 46, name: '宮崎県' },
    { id: 47, name: '鹿児島県' },
    { id: 48, name: '沖縄県' }
  ]
end

app/models/record.rb
class Record < ApplicationRecord
belongs_to :user
belongs_to :item
has_one :address
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :genre
  has_many  :comments
  has_many  :item_comments, dependent: :destroy
  has_one_attached :image
  validates :image, presence: true
  validates :nickname, presence: true
  validates :prefecture, presence: true
  validates :prefecture_id, numericality: { other_than: 1 }
  validates :genre_id,  numericality: { other_than: 1 }
  has_many :opuses, dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :likes
  has_many :like_opuses, through: :likes, source: :opus
  def liked_by?(opus_id)
    likes.where(opus_id: opus_id).exists?
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>DefStyle</title>
   <link rel="stylesheet" href="./css/reset.css">
    <link rel="stylesheet" href="./css/style.css">
  <script src="http://code.jquery.com/jquery-3.3.1.min.js" defer></script>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="stylesheet" media="all" href="css/style.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js"></script>
<script src="js/script.js"></script>
<meta name="viewport" content="width=device-width">
  <script type="text/javascript" src="https://js.pay.jp/v1/"></script>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_pack_tag 'application' %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>

<body>
  <%= yield %>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: model.errors.count,
                 resource: model.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer id="footer">
	<p>株式会社Def-Style TEL:999-999-999</p>
</footer>

app/views/shared/_header.header.erb
<div id="header-footer">
		<div class="list-boxs">
			<%= link_to "作品", opuses_path, class: "btn btn-outline-light" %>
		</div>
		<div class="list-boxs">
			<%= link_to "商品", items_path, class: "btn btn-outline-light" %>
		</div>

		<% if user_signed_in? %>
		<div class="list-boxs">
			<%= link_to "Likes", user_index_like_path(current_user.id), class: "btn btn-outline-light" %>
		</div>
		<div class="list-boxs">
			<%= link_to "マイページ", user_path(current_user.id), class: "btn btn-outline-light" %>
		</div>
		<div class="list-boxs">
			<%= link_to 'log out', destroy_user_session_path, method: :delete, class: "btn btn-outline-light" %>
		</div>
		<% else %>
		<div class="list-boxs">
			<%= link_to "top", root_path, class: "btn btn-outline-light" %>
		</div>
		<div class="list-boxs">
			<%= link_to "log in", new_user_session_path, class:"btn btn-outline-light" %>
		</div>
		<div class="list-boxs">
			<%= link_to "新規登録", new_user_registration_path, class:"btn btn-outline-light" %>
		</div>
		<% end %>
		
		
			<script>
				$('.list-boxs').show(800);
			</script>
	</div>

app/views/shared/_header.html.erb
<div id="header">
	
	<div id="header-header">
			<img src="/assets/mainimg.jpg" alt="" id= "main-image" >
		<script>
			$('#main-image').fadeIn(4500);
		</script>
	</div>
	<%= render "shared/header.header" %>
</div>

app/views/shared/_header2.html.erb
<div id="header">
	
	<div id="header-header">
			<img src="/assets/mainimage2.jpg" alt="" id= "main-image" >
		<script>
			$('#main-image').fadeIn(4500);
		</script>
	</div>
	<%= render "shared/header.header" %>
</div>