config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "tops#index"
  resources :opuses do
    resources :comments, only: [:create]
    collection do
      get 'search'
    end
  end
  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'
  resources :items do
    resources :item_comments, only: [:create]
    resources :orders, only: [:index, :create]
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show, :edit, :update, :destroy, :index] do
    get 'likes/index' => 'likes#index', as: 'index_like' 
  end
  # resources :likes, only: [:index]
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :record
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :opus
  validates :text, presence: true
end

app/models/days_to_ship.rb
class DaysToShip < ActiveHash::Base
  self.data = [
    {id: 1 , name: "--" },
    {id: 2 , name: "1~2日" },
    {id: 3 , name: "3~4日" },
    {id: 4 , name: "5~8日" },
    {id: 5 , name: "9~20日" }
  ]
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'Rapper' },
    { id: 3, name: 'DJ' },
    { id: 4, name: 'Graffiti artist' },
    { id: 5, name: 'Track maker' },
    { id: 6, name: 'Dancer' },
    { id: 7, name: 'Producer' },
    { id: 8, name: 'Other' }
  ]
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many  :item_comments, dependent: :destroy
  has_many  :records
  has_one_attached :image
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :days_to_ship
  with_options presence: true, numericality: {other_than: 1} do
    validates :days_to_ship_id
  end
  with_options presence: true do
    validates :name, length: { in: 1..50 }
    validates :text, length: { in: 1..500 }
    validates :image
    validates :price, numericality: { greater_than_or_equal_to: 300, less_than_or_equal_to: 9_999_999, message: 'is out of setting range' }
  end
end

app/models/item_comment.rb
class ItemComment < ApplicationRecord
  belongs_to :user
  belongs_to :item
  validates :text, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :opus
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/opus.rb
class Opus < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_one_attached :image
  has_many :likes
  has_many :users, through: :likes
  with_options presence: true do
    validates :title, length: { in: 1..50 }
    validates :description, length: { in: 1..500 }
  end
  validates :video_or_image, presence: true

  def self.search(search)
    if search != ""
      Opus.where('title LIKE(?)', "%#{search}%")
    else
      Opus.all
    end
  end
  private
  def video_or_image
    youtube_url.present? || image.present?
  end
end

app/models/order.rb
class Order
  include ActiveModel::Model
  attr_accessor :postal_code, :prefecture_id, :municipality, :address, :building_name, :phone_number, :token, :user_id, :item_id
  with_options presence: true do
    validates :postal_code, format: {with: /\A[0-9]{3}-[0-9]{4}\z/, message: "is invalid. Include hyphen(-)"}
    validates :prefecture_id, numericality: { other_than: 1 }
    validates :municipality
    validates :address
    validates :phone_number, format: {with: /\A\d{10,11}\z/, message: "ハイフン不要"}
    validates :token
  end
  def save
    record = Record.create(user_id: user_id, item_id: item_id)
    Address.create(postal_code: postal_code, prefecture_id: prefecture_id, municipality: municipality, address: address, building_name: building_name, phone_number: phone_number, record_id: record.id) 
  end
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '北海道' },
    { id: 3, name: '青森県' },
    { id: 4, name: '岩手県' },
    { id: 5, name: '宮城県' },
    { id: 6, name: '秋田県' },
    { id: 7, name: '山形県' },
    { id: 8, name: '福島県' },
    { id: 9, name: '茨城県' },
    { id: 10, name: '栃木県' },
    { id: 11, name: '群馬県' },
    { id: 12, name: '埼玉県' },
    { id: 13, name: '千葉県' },
    { id: 14, name: '東京都' },
    { id: 15, name: '神奈川県' },
    { id: 16, name: '新潟県' },
    { id: 17, name: '富山県' },
    { id: 18, name: '石川県' },
    { id: 19, name: '福井県' },
    { id: 20, name: '山梨県' },
    { id: 21, name: '長野県' },
    { id: 22, name: '岐阜県' },
    { id: 23, name: '静岡県' },
    { id: 24, name: '愛知県' },
    { id: 25, name: '三重県' },
    { id: 26, name: '滋賀県' },
    { id: 27, name: '京都府' },
    { id: 28, name: '大阪府' },
    { id: 29, name: '兵庫県' },
    { id: 30, name: '奈良県' },
    { id: 31, name: '和歌山県' },
    { id: 32, name: '鳥取県' },
    { id: 33, name: '島根県' },
    { id: 34, name: '岡山県' },
    { id: 35, name: '広島県' },
    { id: 36, name: '山口県' },
    { id: 37, name: '徳島県' },
    { id: 38, name: '香川県' },
    { id: 39, name: '愛媛県' },
    { id: 40, name: '高知県' },
    { id: 41, name: '福岡県' },
    { id: 42, name: '佐賀県' },
    { id: 43, name: '長崎県' },
    { id: 44, name: '熊本県' },
    { id: 45, name: '大分県' },
    { id: 46, name: '宮崎県' },
    { id: 47, name: '鹿児島県' },
    { id: 48, name: '沖縄県' }
  ]
end

app/models/record.rb
class Record < ApplicationRecord
belongs_to :user
belongs_to :item
has_one :address
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :genre
  has_many  :comments
  has_many  :item_comments, dependent: :destroy
  has_one_attached :image
  validates :image, presence: true
  validates :nickname, presence: true
  validates :prefecture, presence: true
  validates :prefecture_id, numericality: { other_than: 1 }
  validates :genre_id,  numericality: { other_than: 1 }
  has_many :opuses, dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :likes
  has_many :like_opuses, through: :likes, source: :opus
  def liked_by?(opus_id)
    likes.where(opus_id: opus_id).exists?
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :search]
  before_action :search_item, only: [:index, :search]
  def index
    @items = Item.all
  end
  def new
    @item = Item.new
  end
  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to action: :index
    else
      render action: :new
    end
  end
  def show
    @item = Item.find(params[:id])
    @item_comment = ItemComment.new
    @item_comments = @item.item_comments.includes(:user)
  end
  def edit
    @item = Item.find(params[:id])
  end
  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to action: :index
    else
      render action: :edit
    end
  end
  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to action: :index
  end
  def search
    @results = @p.result.includes(:user).order("created_at DESC")  # 検索条件にマッチした商品の情報を取得
  end

  
  private
    def item_params
      params.require(:item).permit(:name, :text, :days_to_ship_id, :image, :price).merge(user_id: current_user.id)
    end
    def search_item
      @p = Item.ransack(params[:q])  # 検索オブジェクトを生成
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/opuses_helper.rb
module OpusesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_form.html.erb
<div class="item-form">
    <div class="item-form-box">
     <%= bootstrap_form_with model: item, local: true do |f| %>
        <%= render '/shared/error_messages', model: f.object %>
        <%= f.text_field :name, placeholder: "title", rows: "10" %>
        <%= f.text_area :text, placeholder: "text", rows: "6" %>
        <%= f.file_field :image, id:"item-image" %>
        <%= f.collection_select(:days_to_ship_id, DaysToShip.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <%= f.text_field :price, placeholder: "price", rows: "10" %>
        <%= f.submit "出品する" ,class:"btn btn-primary btn-lg" %>
      <button type="button" class="btn btn-warning"><%= link_to 'もどる', items_path, class:"btn" %></button>
      <% end %>
    </div>
</div>

app/views/items/edit.html.erb
 <%= render "shared/header.header" %>
 <%= render partial:"form", locals: { item: @item }%>
 <%= render "shared/footer" %>

app/views/items/index.html.erb
<%= render "shared/header.header" %>
<div class="opus-index">
	
	  <div class='item-contents'>
    <h2 class='title'>新着のグッズ</h2>
    <%= link_to '作品を出品してみる', new_item_path, class: "btn btn-dark btn-lg" %>
    <div>
		<%= search_form_for @p, url: search_items_path do |f| %>
				<%= f.text_field :name_eq, placeholder: "商品名を検索", class: 'input'%>
				<button class="btn btn-primary btn-lg">検索</button>
			<% end %>
		</div>
    <ul class='item-lists'>
      <% @items.each do |item| %>
      <%# 商品のインスタンス変数になにか入っている場合、中身のすべてを展開できるようにしましょう %>
      <li class='list'>
						<%= link_to item_path(item.id) do %>
						<div class='item-img-content'>
							<%= image_tag item.image.variant(resize: '500x500'), class: 'item-img' if item.image.attached? %>
						</div>
						<div class='item-info'>
							<h3 class='item-name'>
								<%= item.name %>
							</h3>
							<div class='item-price'>
								<span>¥<%= item.price %></span>
							</div>
						</div>
						<% end %>
        
      </li>
      <% end %>
    </ul>
  </div>
</div>
<%= render "shared/footer" %>

app/views/items/new.html.erb
<%= render "shared/header.header" %>
<%= render partial:"form", locals: { item: @item }%>
<%= render "shared/footer" %> 

app/views/items/search.html.erb
<%= render "shared/header.header" %>
<div class="search">
  <div class="search-menu">
    <%= search_form_for @p, url: search_items_path do |f| %>
          <%= f.text_field :name_eq, placeholder: "価値観を検索", class: 'input'%>
          <button class="btn btn-primary btn-lg">検索</button>
        <% end %>
  </div>
    <div class="search-index">
      <% if @results.length !=0 %>
        <% @results.each do |item| %>
          <div class='resurt-lists'>
           <div class="resurt-list">
            
                  <div class='resurt-img-content'>
                    
                      <%= image_tag item.image.variant(resize: '500x500'), class: 'item-img' if item.image.attached? %>
                    
                  </div>
                    <div class='resurt-title'>
                      <%= item.name %>
                    </div>
                    <div class="resurt-btn">
                      <%= link_to "商品をチェック", item_path(item.id),class: "btn btn-danger" %>
                    </div>
                
          
           </div>
                
          </div>
        <% end %>
      <% else %>
        該当する商品はありません
      <% end %>
  </div>
</div>

app/views/items/show.html.erb
<%= render "shared/header.header" %>
<div class="item-show">
  <div class="item-show-image">
    <%= image_tag @item.image if @item.image.attached? %>
  </div>
  <script>
   $('.item-show-image').fadeIn(3000);
  </script>
  <div class="item-show-details">
    <div class="item-show-name">
      <th>商品名</th><br>
      <%= @item.name %>
    </div>
    <div class="item-show-text">
      <th>商品説明</th><br>
      <%= @item.text %>
    </div>
    <div class="item-show-days">
      <th>発送までの日時</th><br>
      <%= @item.days_to_ship.name %>
    </div>
    <div class="item-show-price">
      <th>金額</th><br>
      <p>¥<%= @item.price %></p>
    </div>
  </div>
  <div class="item-show-judge">
  <% if current_user.id == @item.user.id %>
    <%= link_to '編集', edit_item_path(@item.id), class:"btn btn-primary btn-lg" %>
    <%= link_to '削除', item_path(@item.id), method: :delete, class:"btn btn-danger btn-lg" %>
    <%= link_to 'もどる', items_path, class:"btn btn-warning btn-lg" %>
  <% else %>
  <%= link_to '購入', item_orders_path(@item.id), class:"btn btn-danger btn-lg"%>
  <%= link_to 'もどる', items_path, class:"btn btn-warning btn-lg" %>
   <% end %>
  </div>
  <div class="item-show-comment">
        <div id='messages'>
          <% @item_comments.reverse_each do |message| %>
            <p><%= message.text %>:by<%= message.user.nickname %> 投稿日時:<%= l message.created_at %></p>
            
          <% end %>
        </div>
        
  </div>
      <div class="item-show-send">
          <%= bootstrap_form_with model: [@item,@item_comment] do |form| %>
          <%= form.text_field :text %>
          <button class="btn btn-primary btn-lg">コメント</button>
          <% end %>
      </div>
</div>

        